[package]
name = "finn_chat_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.14"
mongodb = "2.3.0"
bson = "2.4.0"
futures = "0.3.24"
tokio = "1.21.1"